#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x687393EE37D128F8 (matthieu@herrb.eu)
#
Name     : libXvMC
Version  : 1.0.10
Release  : 15
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.10.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.10.tar.gz
Source99 : http://xorg.freedesktop.org/releases/individual/lib/libXvMC-1.0.10.tar.gz.sig
Summary  : The XvMC Library
Group    : Development/Tools
License  : MIT
Requires: libXvMC-lib
Requires: libXvMC-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32videoproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xv)
BuildRequires : pkgconfig(videoproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xv)

%description
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXvMC package.
Group: Development
Requires: libXvMC-lib
Provides: libXvMC-devel

%description dev
dev components for the libXvMC package.


%package dev32
Summary: dev32 components for the libXvMC package.
Group: Default
Requires: libXvMC-lib32
Requires: libXvMC-dev

%description dev32
dev32 components for the libXvMC package.


%package doc
Summary: doc components for the libXvMC package.
Group: Documentation

%description doc
doc components for the libXvMC package.


%package lib
Summary: lib components for the libXvMC package.
Group: Libraries

%description lib
lib components for the libXvMC package.


%package lib32
Summary: lib32 components for the libXvMC package.
Group: Default

%description lib32
lib32 components for the libXvMC package.


%prep
%setup -q -n libXvMC-1.0.10
pushd ..
cp -a libXvMC-1.0.10 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1508609342
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1508609342
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XvMClib.h
/usr/lib64/libXvMC.so
/usr/lib64/libXvMCW.so
/usr/lib64/pkgconfig/xvmc.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXvMC.so
/usr/lib32/libXvMCW.so
/usr/lib32/pkgconfig/32xvmc.pc
/usr/lib32/pkgconfig/xvmc.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/libXvMC/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXvMC.so.1
/usr/lib64/libXvMC.so.1.0.0
/usr/lib64/libXvMCW.so.1
/usr/lib64/libXvMCW.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXvMC.so.1
/usr/lib32/libXvMC.so.1.0.0
/usr/lib32/libXvMCW.so.1
/usr/lib32/libXvMCW.so.1.0.0
